from fish_vgg16_config import fish_vgg16_config
from fish_res50_config import fish_res50_config
from fish_squeezeDet_config import fish_squeezeDet_config
from fish_squeezeDetPlus_config import fish_squeezeDetPlus_config